version: '3.4'

services:
  cups:
    image: korylprince/cups-gcp-cups:v1.0.1
    networks:
      - cups
    ports:
      - 631:631
    volumes:
      - cups_data:/cups
    environment:
      CUPS_SERVER_ALIAS: "cups.${DOMAIN} cups"
      CUPS_USER: administrator
      CUPS_PASS_FILE: /run/secrets/cups_admin_pass
      FCM_ENABLED: "true"
      XMPP_JID_FILE: /run/secrets/cups_xmpp_jid
      REFRESH_TOKEN_FILE: /run/secrets/cups_refresh_token
      PROXY_NAME: "My Connector ID"
      LOG_LEVEL: "INFO"
    deploy:
      mode: replicated
      replicas: 1
    secrets:
      - cups_admin_pass
      - cups_xmpp_jid
      - cups_refresh_token

  resumer:
    image: korylprince/cups-gcp-resumer:v1.0.0
    networks:
      - cups
    environment:
      CUPS_SERVER: cups:631
      RESUME_PRINTERS: "printer-name-1 printer-name-2"
    deploy:
      mode: replicated
      replicas: 1

networks:
  cups:

secrets:
  cups_admin_pass:
    external: true
  cups_xmpp_jid:
    external: true
  cups_refresh_token:
    external: true

volumes:
  cups_data:
    name: cups_data
